// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CommandResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static CommandResponse getRootAsCommandResponse(ByteBuffer _bb) { return getRootAsCommandResponse(_bb, new CommandResponse()); }
  public static CommandResponse getRootAsCommandResponse(ByteBuffer _bb, CommandResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CommandResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long commandId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean success() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String errorMessage() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorMessageAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer errorMessageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createCommandResponse(FlatBufferBuilder builder,
      long commandId,
      boolean success,
      int errorMessageOffset) {
    builder.startTable(3);
    CommandResponse.addErrorMessage(builder, errorMessageOffset);
    CommandResponse.addCommandId(builder, commandId);
    CommandResponse.addSuccess(builder, success);
    return CommandResponse.endCommandResponse(builder);
  }

  public static void startCommandResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addCommandId(FlatBufferBuilder builder, long commandId) { builder.addInt(0, (int) commandId, (int) 0L); }
  public static void addSuccess(FlatBufferBuilder builder, boolean success) { builder.addBoolean(1, success, false); }
  public static void addErrorMessage(FlatBufferBuilder builder, int errorMessageOffset) { builder.addOffset(2, errorMessageOffset, 0); }
  public static int endCommandResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CommandResponse get(int j) { return get(new CommandResponse(), j); }
    public CommandResponse get(CommandResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

