// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

@SuppressWarnings("unused")
public final class CommandPayload {
  private CommandPayload() { }
  public static final byte NONE = 0;
  public static final byte SendChatCommand = 1;
  public static final byte KickPlayerCommand = 2;
  public static final byte TeleportPlayerCommand = 3;
  public static final byte GiveItemCommand = 4;

  public static final String[] names = { "NONE", "SendChatCommand", "KickPlayerCommand", "TeleportPlayerCommand", "GiveItemCommand", };

  public static String name(int e) { return names[e]; }
}

