// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

@SuppressWarnings("unused")
public final class DamageType {
  private DamageType() { }
  public static final byte Unknown = 0;
  public static final byte Generic = 1;
  public static final byte Bullet = 2;
  public static final byte Slash = 3;
  public static final byte Blunt = 4;
  public static final byte Fall = 5;
  public static final byte Radiation = 6;
  public static final byte Bite = 7;
  public static final byte Stab = 8;
  public static final byte Explosion = 9;
  public static final byte Heat = 10;
  public static final byte Cold = 11;
  public static final byte Bleeding = 12;
  public static final byte Poison = 13;
  public static final byte Hunger = 14;
  public static final byte Thirst = 15;
  public static final byte Drowned = 16;
  public static final byte ElectricShock = 17;

  public static final String[] names = { "Unknown", "Generic", "Bullet", "Slash", "Blunt", "Fall", "Radiation", "Bite", "Stab", "Explosion", "Heat", "Cold", "Bleeding", "Poison", "Hunger", "Thirst", "Drowned", "ElectricShock", };

  public static String name(int e) { return names[e]; }
}

