// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EntityKilledEvent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static EntityKilledEvent getRootAsEntityKilledEvent(ByteBuffer _bb) { return getRootAsEntityKilledEvent(_bb, new EntityKilledEvent()); }
  public static EntityKilledEvent getRootAsEntityKilledEvent(ByteBuffer _bb, EntityKilledEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EntityKilledEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String entityId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer entityIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer entityIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String entityType() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer entityTypeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer entityTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String killerId() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer killerIdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer killerIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createEntityKilledEvent(FlatBufferBuilder builder,
      int entityIdOffset,
      int entityTypeOffset,
      int killerIdOffset) {
    builder.startTable(3);
    EntityKilledEvent.addKillerId(builder, killerIdOffset);
    EntityKilledEvent.addEntityType(builder, entityTypeOffset);
    EntityKilledEvent.addEntityId(builder, entityIdOffset);
    return EntityKilledEvent.endEntityKilledEvent(builder);
  }

  public static void startEntityKilledEvent(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addEntityId(FlatBufferBuilder builder, int entityIdOffset) { builder.addOffset(0, entityIdOffset, 0); }
  public static void addEntityType(FlatBufferBuilder builder, int entityTypeOffset) { builder.addOffset(1, entityTypeOffset, 0); }
  public static void addKillerId(FlatBufferBuilder builder, int killerIdOffset) { builder.addOffset(2, killerIdOffset, 0); }
  public static int endEntityKilledEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // entity_id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EntityKilledEvent get(int j) { return get(new EntityKilledEvent(), j); }
    public EntityKilledEvent get(EntityKilledEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

