// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

@SuppressWarnings("unused")
public final class EventPayload {
  private EventPayload() { }
  public static final byte NONE = 0;
  public static final byte PlayerConnectedEvent = 1;
  public static final byte PlayerDisconnectedEvent = 2;
  public static final byte PlayerDamageEvent = 3;
  public static final byte PlayerDeathEvent = 4;
  public static final byte PlayerRespawnEvent = 5;
  public static final byte ChatMessageEvent = 6;
  public static final byte StructurePlacedEvent = 7;
  public static final byte StructureDestroyedEvent = 8;
  public static final byte EntitySpawnedEvent = 9;
  public static final byte EntityKilledEvent = 10;
  public static final byte ItemCraftedEvent = 11;

  public static final String[] names = { "NONE", "PlayerConnectedEvent", "PlayerDisconnectedEvent", "PlayerDamageEvent", "PlayerDeathEvent", "PlayerRespawnEvent", "ChatMessageEvent", "StructurePlacedEvent", "StructureDestroyedEvent", "EntitySpawnedEvent", "EntityKilledEvent", "ItemCraftedEvent", };

  public static String name(int e) { return names[e]; }
}

