// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GameEvent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static GameEvent getRootAsGameEvent(ByteBuffer _bb) { return getRootAsGameEvent(_bb, new GameEvent()); }
  public static GameEvent getRootAsGameEvent(ByteBuffer _bb, GameEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GameEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String eventName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer eventNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long timestamp() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte payloadType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table payload(Table obj) { int o = __offset(10); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createGameEvent(FlatBufferBuilder builder,
      int eventNameOffset,
      long timestamp,
      byte payloadType,
      int payloadOffset) {
    builder.startTable(4);
    GameEvent.addTimestamp(builder, timestamp);
    GameEvent.addPayload(builder, payloadOffset);
    GameEvent.addEventName(builder, eventNameOffset);
    GameEvent.addPayloadType(builder, payloadType);
    return GameEvent.endGameEvent(builder);
  }

  public static void startGameEvent(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addEventName(FlatBufferBuilder builder, int eventNameOffset) { builder.addOffset(0, eventNameOffset, 0); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(1, timestamp, 0L); }
  public static void addPayloadType(FlatBufferBuilder builder, byte payloadType) { builder.addByte(2, payloadType, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(3, payloadOffset, 0); }
  public static int endGameEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // event_name
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GameEvent get(int j) { return get(new GameEvent(), j); }
    public GameEvent get(GameEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

