// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GameHook extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static GameHook getRootAsGameHook(ByteBuffer _bb) { return getRootAsGameHook(_bb, new GameHook()); }
  public static GameHook getRootAsGameHook(ByteBuffer _bb, GameHook obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GameHook __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long hookId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String hookName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hookNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer hookNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long timestamp() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte payloadType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table payload(Table obj) { int o = __offset(12); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createGameHook(FlatBufferBuilder builder,
      long hookId,
      int hookNameOffset,
      long timestamp,
      byte payloadType,
      int payloadOffset) {
    builder.startTable(5);
    GameHook.addTimestamp(builder, timestamp);
    GameHook.addPayload(builder, payloadOffset);
    GameHook.addHookName(builder, hookNameOffset);
    GameHook.addHookId(builder, hookId);
    GameHook.addPayloadType(builder, payloadType);
    return GameHook.endGameHook(builder);
  }

  public static void startGameHook(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addHookId(FlatBufferBuilder builder, long hookId) { builder.addInt(0, (int) hookId, (int) 0L); }
  public static void addHookName(FlatBufferBuilder builder, int hookNameOffset) { builder.addOffset(1, hookNameOffset, 0); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(2, timestamp, 0L); }
  public static void addPayloadType(FlatBufferBuilder builder, byte payloadType) { builder.addByte(3, payloadType, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(4, payloadOffset, 0); }
  public static int endGameHook(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // hook_name
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GameHook get(int j) { return get(new GameHook(), j); }
    public GameHook get(GameHook obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

