// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GameCommand extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static GameCommand getRootAsGameCommand(ByteBuffer _bb) { return getRootAsGameCommand(_bb, new GameCommand()); }
  public static GameCommand getRootAsGameCommand(ByteBuffer _bb, GameCommand obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GameCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long commandId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String commandName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer commandNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer commandNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public byte payloadType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table payload(Table obj) { int o = __offset(10); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createGameCommand(FlatBufferBuilder builder,
      long commandId,
      int commandNameOffset,
      byte payloadType,
      int payloadOffset) {
    builder.startTable(4);
    GameCommand.addPayload(builder, payloadOffset);
    GameCommand.addCommandName(builder, commandNameOffset);
    GameCommand.addCommandId(builder, commandId);
    GameCommand.addPayloadType(builder, payloadType);
    return GameCommand.endGameCommand(builder);
  }

  public static void startGameCommand(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addCommandId(FlatBufferBuilder builder, long commandId) { builder.addInt(0, (int) commandId, (int) 0L); }
  public static void addCommandName(FlatBufferBuilder builder, int commandNameOffset) { builder.addOffset(1, commandNameOffset, 0); }
  public static void addPayloadType(FlatBufferBuilder builder, byte payloadType) { builder.addByte(2, payloadType, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(3, payloadOffset, 0); }
  public static int endGameCommand(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // command_name
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GameCommand get(int j) { return get(new GameCommand(), j); }
    public GameCommand get(GameCommand obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

