// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GiveItemCommand extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static GiveItemCommand getRootAsGiveItemCommand(ByteBuffer _bb) { return getRootAsGiveItemCommand(_bb, new GiveItemCommand()); }
  public static GiveItemCommand getRootAsGiveItemCommand(ByteBuffer _bb, GiveItemCommand obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GiveItemCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String playerId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer playerIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer playerIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String itemName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer itemNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer itemNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int amount() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 1; }

  public static int createGiveItemCommand(FlatBufferBuilder builder,
      int playerIdOffset,
      int itemNameOffset,
      int amount) {
    builder.startTable(3);
    GiveItemCommand.addAmount(builder, amount);
    GiveItemCommand.addItemName(builder, itemNameOffset);
    GiveItemCommand.addPlayerId(builder, playerIdOffset);
    return GiveItemCommand.endGiveItemCommand(builder);
  }

  public static void startGiveItemCommand(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addPlayerId(FlatBufferBuilder builder, int playerIdOffset) { builder.addOffset(0, playerIdOffset, 0); }
  public static void addItemName(FlatBufferBuilder builder, int itemNameOffset) { builder.addOffset(1, itemNameOffset, 0); }
  public static void addAmount(FlatBufferBuilder builder, int amount) { builder.addInt(2, amount, 1); }
  public static int endGiveItemCommand(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // player_id
    builder.required(o, 6);  // item_name
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GiveItemCommand get(int j) { return get(new GiveItemCommand(), j); }
    public GiveItemCommand get(GiveItemCommand obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

