// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class HookResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static HookResponse getRootAsHookResponse(ByteBuffer _bb) { return getRootAsHookResponse(_bb, new HookResponse()); }
  public static HookResponse getRootAsHookResponse(ByteBuffer _bb, HookResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public HookResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long hookId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public byte payloadType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table payload(Table obj) { int o = __offset(8); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createHookResponse(FlatBufferBuilder builder,
      long hookId,
      byte payloadType,
      int payloadOffset) {
    builder.startTable(3);
    HookResponse.addPayload(builder, payloadOffset);
    HookResponse.addHookId(builder, hookId);
    HookResponse.addPayloadType(builder, payloadType);
    return HookResponse.endHookResponse(builder);
  }

  public static void startHookResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addHookId(FlatBufferBuilder builder, long hookId) { builder.addInt(0, (int) hookId, (int) 0L); }
  public static void addPayloadType(FlatBufferBuilder builder, byte payloadType) { builder.addByte(1, payloadType, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(2, payloadOffset, 0); }
  public static int endHookResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public HookResponse get(int j) { return get(new HookResponse(), j); }
    public HookResponse get(HookResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

