// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

@SuppressWarnings("unused")
public final class HookPayload {
  private HookPayload() { }
  public static final byte NONE = 0;
  public static final byte PlayerConnectingHook = 1;
  public static final byte PlayerTakingDamageHook = 2;
  public static final byte PlayerChatHook = 3;
  public static final byte PlayerBuildHook = 4;
  public static final byte PlayerLootHook = 5;
  public static final byte PlayerCraftHook = 6;

  public static final String[] names = { "NONE", "PlayerConnectingHook", "PlayerTakingDamageHook", "PlayerChatHook", "PlayerBuildHook", "PlayerLootHook", "PlayerCraftHook", };

  public static String name(int e) { return names[e]; }
}

