// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

@SuppressWarnings("unused")
public final class HookResponsePayload {
  private HookResponsePayload() { }
  public static final byte NONE = 0;
  public static final byte PlayerConnectingResponse = 1;
  public static final byte PlayerDamageResponse = 2;
  public static final byte PlayerChatResponse = 3;
  public static final byte PlayerBuildResponse = 4;
  public static final byte PlayerLootResponse = 5;
  public static final byte PlayerCraftResponse = 6;

  public static final String[] names = { "NONE", "PlayerConnectingResponse", "PlayerDamageResponse", "PlayerChatResponse", "PlayerBuildResponse", "PlayerLootResponse", "PlayerCraftResponse", };

  public static String name(int e) { return names[e]; }
}

