// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

@SuppressWarnings("unused")
public final class MessageType {
  private MessageType() { }
  public static final byte Event = 0;
  public static final byte Hook = 1;
  public static final byte HookResponse = 2;
  public static final byte Command = 3;
  public static final byte CommandResponse = 4;

  public static final String[] names = { "Event", "Hook", "HookResponse", "Command", "CommandResponse", };

  public static String name(int e) { return names[e]; }
}

