// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

@SuppressWarnings("unused")
public final class MessagePayload {
  private MessagePayload() { }
  public static final byte NONE = 0;
  public static final byte GameEvent = 1;
  public static final byte GameHook = 2;
  public static final byte HookResponse = 3;
  public static final byte GameCommand = 4;
  public static final byte CommandResponse = 5;

  public static final String[] names = { "NONE", "GameEvent", "GameHook", "HookResponse", "GameCommand", "CommandResponse", };

  public static String name(int e) { return names[e]; }
}

