// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerTakingDamageHook extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerTakingDamageHook getRootAsPlayerTakingDamageHook(ByteBuffer _bb) { return getRootAsPlayerTakingDamageHook(_bb, new PlayerTakingDamageHook()); }
  public static PlayerTakingDamageHook getRootAsPlayerTakingDamageHook(ByteBuffer _bb, PlayerTakingDamageHook obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerTakingDamageHook __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String playerId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer playerIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer playerIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public float damage() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public byte damageType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String attackerId() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer attackerIdAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer attackerIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createPlayerTakingDamageHook(FlatBufferBuilder builder,
      int playerIdOffset,
      float damage,
      byte damageType,
      int attackerIdOffset) {
    builder.startTable(4);
    PlayerTakingDamageHook.addAttackerId(builder, attackerIdOffset);
    PlayerTakingDamageHook.addDamage(builder, damage);
    PlayerTakingDamageHook.addPlayerId(builder, playerIdOffset);
    PlayerTakingDamageHook.addDamageType(builder, damageType);
    return PlayerTakingDamageHook.endPlayerTakingDamageHook(builder);
  }

  public static void startPlayerTakingDamageHook(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addPlayerId(FlatBufferBuilder builder, int playerIdOffset) { builder.addOffset(0, playerIdOffset, 0); }
  public static void addDamage(FlatBufferBuilder builder, float damage) { builder.addFloat(1, damage, 0.0f); }
  public static void addDamageType(FlatBufferBuilder builder, byte damageType) { builder.addByte(2, damageType, 0); }
  public static void addAttackerId(FlatBufferBuilder builder, int attackerIdOffset) { builder.addOffset(3, attackerIdOffset, 0); }
  public static int endPlayerTakingDamageHook(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // player_id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerTakingDamageHook get(int j) { return get(new PlayerTakingDamageHook(), j); }
    public PlayerTakingDamageHook get(PlayerTakingDamageHook obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

