// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerLootHook extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerLootHook getRootAsPlayerLootHook(ByteBuffer _bb) { return getRootAsPlayerLootHook(_bb, new PlayerLootHook()); }
  public static PlayerLootHook getRootAsPlayerLootHook(ByteBuffer _bb, PlayerLootHook obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerLootHook __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String playerId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer playerIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer playerIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String containerId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer containerIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer containerIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createPlayerLootHook(FlatBufferBuilder builder,
      int playerIdOffset,
      int containerIdOffset) {
    builder.startTable(2);
    PlayerLootHook.addContainerId(builder, containerIdOffset);
    PlayerLootHook.addPlayerId(builder, playerIdOffset);
    return PlayerLootHook.endPlayerLootHook(builder);
  }

  public static void startPlayerLootHook(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPlayerId(FlatBufferBuilder builder, int playerIdOffset) { builder.addOffset(0, playerIdOffset, 0); }
  public static void addContainerId(FlatBufferBuilder builder, int containerIdOffset) { builder.addOffset(1, containerIdOffset, 0); }
  public static int endPlayerLootHook(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // player_id
    builder.required(o, 6);  // container_id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerLootHook get(int j) { return get(new PlayerLootHook(), j); }
    public PlayerLootHook get(PlayerLootHook obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

