// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerDamageResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerDamageResponse getRootAsPlayerDamageResponse(ByteBuffer _bb) { return getRootAsPlayerDamageResponse(_bb, new PlayerDamageResponse()); }
  public static PlayerDamageResponse getRootAsPlayerDamageResponse(ByteBuffer _bb, PlayerDamageResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerDamageResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float modifiedDamage() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean cancel() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createPlayerDamageResponse(FlatBufferBuilder builder,
      float modifiedDamage,
      boolean cancel) {
    builder.startTable(2);
    PlayerDamageResponse.addModifiedDamage(builder, modifiedDamage);
    PlayerDamageResponse.addCancel(builder, cancel);
    return PlayerDamageResponse.endPlayerDamageResponse(builder);
  }

  public static void startPlayerDamageResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addModifiedDamage(FlatBufferBuilder builder, float modifiedDamage) { builder.addFloat(0, modifiedDamage, 0.0f); }
  public static void addCancel(FlatBufferBuilder builder, boolean cancel) { builder.addBoolean(1, cancel, false); }
  public static int endPlayerDamageResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerDamageResponse get(int j) { return get(new PlayerDamageResponse(), j); }
    public PlayerDamageResponse get(PlayerDamageResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

