// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerDisconnectedEvent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerDisconnectedEvent getRootAsPlayerDisconnectedEvent(ByteBuffer _bb) { return getRootAsPlayerDisconnectedEvent(_bb, new PlayerDisconnectedEvent()); }
  public static PlayerDisconnectedEvent getRootAsPlayerDisconnectedEvent(ByteBuffer _bb, PlayerDisconnectedEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerDisconnectedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String playerId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer playerIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer playerIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String playerName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer playerNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer playerNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String reason() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reasonAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer reasonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createPlayerDisconnectedEvent(FlatBufferBuilder builder,
      int playerIdOffset,
      int playerNameOffset,
      int reasonOffset) {
    builder.startTable(3);
    PlayerDisconnectedEvent.addReason(builder, reasonOffset);
    PlayerDisconnectedEvent.addPlayerName(builder, playerNameOffset);
    PlayerDisconnectedEvent.addPlayerId(builder, playerIdOffset);
    return PlayerDisconnectedEvent.endPlayerDisconnectedEvent(builder);
  }

  public static void startPlayerDisconnectedEvent(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addPlayerId(FlatBufferBuilder builder, int playerIdOffset) { builder.addOffset(0, playerIdOffset, 0); }
  public static void addPlayerName(FlatBufferBuilder builder, int playerNameOffset) { builder.addOffset(1, playerNameOffset, 0); }
  public static void addReason(FlatBufferBuilder builder, int reasonOffset) { builder.addOffset(2, reasonOffset, 0); }
  public static int endPlayerDisconnectedEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // player_id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerDisconnectedEvent get(int j) { return get(new PlayerDisconnectedEvent(), j); }
    public PlayerDisconnectedEvent get(PlayerDisconnectedEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

