// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerConnectingResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerConnectingResponse getRootAsPlayerConnectingResponse(ByteBuffer _bb) { return getRootAsPlayerConnectingResponse(_bb, new PlayerConnectingResponse()); }
  public static PlayerConnectingResponse getRootAsPlayerConnectingResponse(ByteBuffer _bb, PlayerConnectingResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerConnectingResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean allow() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public String denyReason() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer denyReasonAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer denyReasonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createPlayerConnectingResponse(FlatBufferBuilder builder,
      boolean allow,
      int denyReasonOffset) {
    builder.startTable(2);
    PlayerConnectingResponse.addDenyReason(builder, denyReasonOffset);
    PlayerConnectingResponse.addAllow(builder, allow);
    return PlayerConnectingResponse.endPlayerConnectingResponse(builder);
  }

  public static void startPlayerConnectingResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addAllow(FlatBufferBuilder builder, boolean allow) { builder.addBoolean(0, allow, true); }
  public static void addDenyReason(FlatBufferBuilder builder, int denyReasonOffset) { builder.addOffset(1, denyReasonOffset, 0); }
  public static int endPlayerConnectingResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerConnectingResponse get(int j) { return get(new PlayerConnectingResponse(), j); }
    public PlayerConnectingResponse get(PlayerConnectingResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

