// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerCraftResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerCraftResponse getRootAsPlayerCraftResponse(ByteBuffer _bb) { return getRootAsPlayerCraftResponse(_bb, new PlayerCraftResponse()); }
  public static PlayerCraftResponse getRootAsPlayerCraftResponse(ByteBuffer _bb, PlayerCraftResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerCraftResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int modifiedAmount() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean cancel() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createPlayerCraftResponse(FlatBufferBuilder builder,
      int modifiedAmount,
      boolean cancel) {
    builder.startTable(2);
    PlayerCraftResponse.addModifiedAmount(builder, modifiedAmount);
    PlayerCraftResponse.addCancel(builder, cancel);
    return PlayerCraftResponse.endPlayerCraftResponse(builder);
  }

  public static void startPlayerCraftResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addModifiedAmount(FlatBufferBuilder builder, int modifiedAmount) { builder.addInt(0, modifiedAmount, 0); }
  public static void addCancel(FlatBufferBuilder builder, boolean cancel) { builder.addBoolean(1, cancel, false); }
  public static int endPlayerCraftResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerCraftResponse get(int j) { return get(new PlayerCraftResponse(), j); }
    public PlayerCraftResponse get(PlayerCraftResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

