// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerDeathEvent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerDeathEvent getRootAsPlayerDeathEvent(ByteBuffer _bb) { return getRootAsPlayerDeathEvent(_bb, new PlayerDeathEvent()); }
  public static PlayerDeathEvent getRootAsPlayerDeathEvent(ByteBuffer _bb, PlayerDeathEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerDeathEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String playerId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer playerIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer playerIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String killerId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer killerIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer killerIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String weapon() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer weaponAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer weaponInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createPlayerDeathEvent(FlatBufferBuilder builder,
      int playerIdOffset,
      int killerIdOffset,
      int weaponOffset) {
    builder.startTable(3);
    PlayerDeathEvent.addWeapon(builder, weaponOffset);
    PlayerDeathEvent.addKillerId(builder, killerIdOffset);
    PlayerDeathEvent.addPlayerId(builder, playerIdOffset);
    return PlayerDeathEvent.endPlayerDeathEvent(builder);
  }

  public static void startPlayerDeathEvent(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addPlayerId(FlatBufferBuilder builder, int playerIdOffset) { builder.addOffset(0, playerIdOffset, 0); }
  public static void addKillerId(FlatBufferBuilder builder, int killerIdOffset) { builder.addOffset(1, killerIdOffset, 0); }
  public static void addWeapon(FlatBufferBuilder builder, int weaponOffset) { builder.addOffset(2, weaponOffset, 0); }
  public static int endPlayerDeathEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // player_id
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerDeathEvent get(int j) { return get(new PlayerDeathEvent(), j); }
    public PlayerDeathEvent get(PlayerDeathEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

