// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerChatResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerChatResponse getRootAsPlayerChatResponse(ByteBuffer _bb) { return getRootAsPlayerChatResponse(_bb, new PlayerChatResponse()); }
  public static PlayerChatResponse getRootAsPlayerChatResponse(ByteBuffer _bb, PlayerChatResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerChatResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String modifiedMessage() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer modifiedMessageAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer modifiedMessageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public boolean block() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createPlayerChatResponse(FlatBufferBuilder builder,
      int modifiedMessageOffset,
      boolean block) {
    builder.startTable(2);
    PlayerChatResponse.addModifiedMessage(builder, modifiedMessageOffset);
    PlayerChatResponse.addBlock(builder, block);
    return PlayerChatResponse.endPlayerChatResponse(builder);
  }

  public static void startPlayerChatResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addModifiedMessage(FlatBufferBuilder builder, int modifiedMessageOffset) { builder.addOffset(0, modifiedMessageOffset, 0); }
  public static void addBlock(FlatBufferBuilder builder, boolean block) { builder.addBoolean(1, block, false); }
  public static int endPlayerChatResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerChatResponse get(int j) { return get(new PlayerChatResponse(), j); }
    public PlayerChatResponse get(PlayerChatResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

