// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerConnectedEvent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerConnectedEvent getRootAsPlayerConnectedEvent(ByteBuffer _bb) { return getRootAsPlayerConnectedEvent(_bb, new PlayerConnectedEvent()); }
  public static PlayerConnectedEvent getRootAsPlayerConnectedEvent(ByteBuffer _bb, PlayerConnectedEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerConnectedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public RustJavaMods.Protocol.PlayerInfo player() { return player(new RustJavaMods.Protocol.PlayerInfo()); }
  public RustJavaMods.Protocol.PlayerInfo player(RustJavaMods.Protocol.PlayerInfo obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createPlayerConnectedEvent(FlatBufferBuilder builder,
      int playerOffset) {
    builder.startTable(1);
    PlayerConnectedEvent.addPlayer(builder, playerOffset);
    return PlayerConnectedEvent.endPlayerConnectedEvent(builder);
  }

  public static void startPlayerConnectedEvent(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addPlayer(FlatBufferBuilder builder, int playerOffset) { builder.addOffset(0, playerOffset, 0); }
  public static int endPlayerConnectedEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // player
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerConnectedEvent get(int j) { return get(new PlayerConnectedEvent(), j); }
    public PlayerConnectedEvent get(PlayerConnectedEvent obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

