// automatically generated by the FlatBuffers compiler, do not modify

package RustJavaMods.Protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PlayerBuildResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PlayerBuildResponse getRootAsPlayerBuildResponse(ByteBuffer _bb) { return getRootAsPlayerBuildResponse(_bb, new PlayerBuildResponse()); }
  public static PlayerBuildResponse getRootAsPlayerBuildResponse(ByteBuffer _bb, PlayerBuildResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerBuildResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean allow() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }

  public static int createPlayerBuildResponse(FlatBufferBuilder builder,
      boolean allow) {
    builder.startTable(1);
    PlayerBuildResponse.addAllow(builder, allow);
    return PlayerBuildResponse.endPlayerBuildResponse(builder);
  }

  public static void startPlayerBuildResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addAllow(FlatBufferBuilder builder, boolean allow) { builder.addBoolean(0, allow, true); }
  public static int endPlayerBuildResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerBuildResponse get(int j) { return get(new PlayerBuildResponse(), j); }
    public PlayerBuildResponse get(PlayerBuildResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

