@echo off
REM Start Rust Development Server (Windows)
REM Automatically updates and starts the server

setlocal enabledelayedexpansion

cd /d "%~dp0"
cd ..
set PROJECT_ROOT=%cd%
set DEV_SERVER=%PROJECT_ROOT%\dev-server
set TOOLS_DIR=%PROJECT_ROOT%\tools

REM Ensure server + Carbon are present and lib DLLs are populated
call "%PROJECT_ROOT%\scripts\ensure-dev-server.bat"
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Failed to prepare dev-server prerequisites
    pause
    exit /b 1
)

echo.
echo ====================================================================
echo            Rust Development Server Starter (Windows)
echo ====================================================================
echo.

REM ensure-dev-server already created/updated dev-server

REM Deploy bridge
echo Deploying Carbon bridge...
if not exist "%DEV_SERVER%\carbon\plugins" mkdir "%DEV_SERVER%\carbon\plugins"

set BRIDGE_DLL=%PROJECT_ROOT%\csharp-bridge\bin\Release\net472\RustJavaBridge.dll
if exist "%BRIDGE_DLL%" (
    copy "%BRIDGE_DLL%" "%DEV_SERVER%\carbon\plugins\" >nul
    echo Bridge deployed
) else (
    echo WARNING: Bridge DLL not found. Run 'scripts\setup.bat' first
)
echo.

REM Create server config
echo Setting up server configuration...
if not exist "%DEV_SERVER%\server\dev-server\cfg" mkdir "%DEV_SERVER%\server\dev-server\cfg"

set SERVER_CFG=%DEV_SERVER%\server\dev-server\cfg\server.cfg
if not exist "%SERVER_CFG%" (
    (
        echo # Rust Development Server Configuration
        echo # Auto-generated by start-dev.bat
        echo.
        echo server.hostname "Dev - Java Mods Testing"
        echo server.description "Development server for Rust-Java Mods"
        echo server.url "https://github.com/EuSouVoce/rust-java-mods-poc"
        echo.
        echo server.port 28015
        echo server.queryport 28016
        echo server.maxplayers 10
        echo.
        echo server.level "Procedural Map"
        echo server.seed 12345
        echo server.worldsize 2000
        echo server.tickrate 30
        echo.
        echo rcon.port 28017
        echo rcon.password dev123456
        echo rcon.web 1
        echo.
        echo server.logfile "logs/rust_%%Y%%m%%d_%%H%%M%%S.txt"
        echo server.wipe_empty true
        echo decay.scale 0.5
    ) > "%SERVER_CFG%"
    echo Server config created
) else (
    echo Server config exists
)
echo.

REM Start server
echo.
echo ====================================================================
echo                      Server Starting... 🚀
echo ====================================================================
echo.
echo Server directory: %DEV_SERVER%
echo Connect via: connect localhost:28015 (in Rust, press F1)
echo RCON: http://localhost:28017 (password: dev123456)
echo.
echo In another terminal, run:
echo   scripts\watch-java.sh
echo.
echo Server logs:
echo   %DEV_SERVER%\logs\rust_server.txt
echo.

cd /d "%DEV_SERVER%"

RustDedicated.exe ^
    -batchmode ^
    -nographics ^
    +server.port 28015 ^
    +server.queryport 28016 ^
    +server.level "Procedural Map" ^
    +server.seed 12345 ^
    +server.worldsize 2000 ^
    +server.maxplayers 10 ^
    +server.hostname "Dev - Java Mods Testing" ^
    +server.identity "dev-server" ^
    +rcon.port 28017 ^
    +rcon.password dev123456 ^
    +rcon.web 1 ^
    -logfile logs/rust_server.txt

pause
